# Generated by Django 3.0.5 on 2020-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
